// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: notify/v1/notify.proto

package notifyv1

import (
	v1 "ecodepost/pb/common/v1"
	_ "ecodepost/pb/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendMsgReq发送消息请求结构
type SendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息模板id
	TplId int64 `protobuf:"varint,1,opt,name=tplId,proto3" json:"tplId,omitempty"`
	// 消息列表
	Msgs []*Msg `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
	// 额外参数, 站内信, 需配合模板使用
	VarLetter *Letter `protobuf:"bytes,3,opt,name=varLetter,proto3" json:"varLetter,omitempty"`
	// 额外参数, 短信, 需配合模板使用
	VarSms *Sms `protobuf:"bytes,4,opt,name=varSms,proto3" json:"varSms,omitempty"`
	// 额外参数, 邮件, 需配合模板使用
	VarEmail *Email `protobuf:"bytes,5,opt,name=varEmail,proto3" json:"varEmail,omitempty"`
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *SendMsgReq) GetTplId() int64 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *SendMsgReq) GetMsgs() []*Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *SendMsgReq) GetVarLetter() *Letter {
	if x != nil {
		return x.VarLetter
	}
	return nil
}

func (x *SendMsgReq) GetVarSms() *Sms {
	if x != nil {
		return x.VarSms
	}
	return nil
}

func (x *SendMsgReq) GetVarEmail() *Email {
	if x != nil {
		return x.VarEmail
	}
	return nil
}

// 消息定义
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息接收者
	Receiver string `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// 备注
	ExtraContent string `protobuf:"bytes,2,opt,name=extraContent,proto3" json:"extraContent,omitempty"`
	// 业务层扩展extraId
	ExtraId string `protobuf:"bytes,3,opt,name=extraId,proto3" json:"extraId,omitempty"`
	// 运营商发送消息时需要的动态变量
	Vars map[string]string `protobuf:"bytes,4,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 模板数据，使用JSON反序列化，存储模板使用的变量，该数据被用于通过Go Html Template渲染最终发送内容
	TplData []byte `protobuf:"bytes,5,opt,name=tplData,proto3" json:"tplData,omitempty"`
	// 消息发送者, uid/topicGuid/空间guid/社区guid等
	Sender string `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Msg) GetExtraContent() string {
	if x != nil {
		return x.ExtraContent
	}
	return ""
}

func (x *Msg) GetExtraId() string {
	if x != nil {
		return x.ExtraId
	}
	return ""
}

func (x *Msg) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *Msg) GetTplData() []byte {
	if x != nil {
		return x.TplData
	}
	return nil
}

func (x *Msg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type Letter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型
	Type v1.NTF_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.NTF_TYPE" json:"type,omitempty"`
	// 对象ID
	TargetId string `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	// 链接
	Link string `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	// 附属数据
	Meta []byte `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *Letter) Reset() {
	*x = Letter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Letter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Letter) ProtoMessage() {}

func (x *Letter) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Letter.ProtoReflect.Descriptor instead.
func (*Letter) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{2}
}

func (x *Letter) GetType() v1.NTF_TYPE {
	if x != nil {
		return x.Type
	}
	return v1.NTF_TYPE_INVALID
}

func (x *Letter) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Letter) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Letter) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

type Sms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sms) Reset() {
	*x = Sms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{3}
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// toName
	ToName string `protobuf:"bytes,1,opt,name=toName,proto3" json:"toName,omitempty"`
	// 主题
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// 抄送
	Cc []string `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{4}
}

func (x *Email) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

// 用户通知
type UserNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 通知ID
	NotificationId int64 `protobuf:"varint,2,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
}

func (x *UserNotification) Reset() {
	*x = UserNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotification) ProtoMessage() {}

func (x *UserNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotification.ProtoReflect.Descriptor instead.
func (*UserNotification) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{5}
}

func (x *UserNotification) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserNotification) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

// 变更用户通知消息状态请求
type UpdateReadStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 通知ID
	NotificationId int64 `protobuf:"varint,2,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
}

func (x *UpdateReadStatusReq) Reset() {
	*x = UpdateReadStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReadStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadStatusReq) ProtoMessage() {}

func (x *UpdateReadStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateReadStatusReq) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateReadStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateReadStatusReq) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type UpdateReadStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateReadStatusRes) Reset() {
	*x = UpdateReadStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReadStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadStatusRes) ProtoMessage() {}

func (x *UpdateReadStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadStatusRes.ProtoReflect.Descriptor instead.
func (*UpdateReadStatusRes) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{7}
}

type GetUnViewCountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUnViewCountReq) Reset() {
	*x = GetUnViewCountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnViewCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnViewCountReq) ProtoMessage() {}

func (x *GetUnViewCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnViewCountReq.ProtoReflect.Descriptor instead.
func (*GetUnViewCountReq) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{8}
}

func (x *GetUnViewCountReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUnViewCountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 未查看的通知数量
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetUnViewCountRes) Reset() {
	*x = GetUnViewCountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnViewCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnViewCountRes) ProtoMessage() {}

func (x *GetUnViewCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnViewCountRes.ProtoReflect.Descriptor instead.
func (*GetUnViewCountRes) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnViewCountRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListUserNotificationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 类型, 为空表示不先定查询类型
	Types []v1.NTF_TYPE `protobuf:"varint,2,rep,packed,name=types,proto3,enum=common.v1.NTF_TYPE" json:"types,omitempty"`
	// 页码
	Pagination *v1.Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListUserNotificationReq) Reset() {
	*x = ListUserNotificationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserNotificationReq) ProtoMessage() {}

func (x *ListUserNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserNotificationReq.ProtoReflect.Descriptor instead.
func (*ListUserNotificationReq) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserNotificationReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListUserNotificationReq) GetTypes() []v1.NTF_TYPE {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListUserNotificationReq) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserNotificationRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前列表数据
	List []*ListUserNotificationItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 总数量
	Pagination *v1.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListUserNotificationRes) Reset() {
	*x = ListUserNotificationRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserNotificationRes) ProtoMessage() {}

func (x *ListUserNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserNotificationRes.ProtoReflect.Descriptor instead.
func (*ListUserNotificationRes) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserNotificationRes) GetList() []*ListUserNotificationItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListUserNotificationRes) GetPagination() *v1.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListUserNotificationItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型
	Type v1.NTF_TYPE `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.NTF_TYPE" json:"type,omitempty"`
	// 对象ID
	TargetId string `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	// 消息外链
	Link string `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	// 附属数据
	Meta []byte `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	// 消息状态
	Status v1.NTF_STATUS `protobuf:"varint,5,opt,name=status,proto3,enum=common.v1.NTF_STATUS" json:"status,omitempty"`
	// 通知ID
	NotificationId int64 `protobuf:"varint,6,opt,name=notificationId,proto3" json:"notificationId,omitempty"`
	// 通知时间
	NotificationTime int64 `protobuf:"varint,7,opt,name=notificationTime,proto3" json:"notificationTime,omitempty"`
	// 发送者Id, 设置成string方便后续扩展, 目前可以全部当成uid来处理
	SenderId string `protobuf:"bytes,8,opt,name=senderId,proto3" json:"senderId,omitempty"`
	// 唯一id
	Id int64 `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListUserNotificationItem) Reset() {
	*x = ListUserNotificationItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListUserNotificationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserNotificationItem) ProtoMessage() {}

func (x *ListUserNotificationItem) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserNotificationItem.ProtoReflect.Descriptor instead.
func (*ListUserNotificationItem) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserNotificationItem) GetType() v1.NTF_TYPE {
	if x != nil {
		return x.Type
	}
	return v1.NTF_TYPE_INVALID
}

func (x *ListUserNotificationItem) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ListUserNotificationItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ListUserNotificationItem) GetMeta() []byte {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListUserNotificationItem) GetStatus() v1.NTF_STATUS {
	if x != nil {
		return x.Status
	}
	return v1.NTF_STATUS_INVALID
}

func (x *ListUserNotificationItem) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *ListUserNotificationItem) GetNotificationTime() int64 {
	if x != nil {
		return x.NotificationTime
	}
	return 0
}

func (x *ListUserNotificationItem) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ListUserNotificationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 请求信息
type ChangeUserAllNotificationStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户ID
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 消息状态
	Status v1.NTF_STATUS `protobuf:"varint,2,opt,name=status,proto3,enum=common.v1.NTF_STATUS" json:"status,omitempty"`
}

func (x *ChangeUserAllNotificationStatusReq) Reset() {
	*x = ChangeUserAllNotificationStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserAllNotificationStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAllNotificationStatusReq) ProtoMessage() {}

func (x *ChangeUserAllNotificationStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAllNotificationStatusReq.ProtoReflect.Descriptor instead.
func (*ChangeUserAllNotificationStatusReq) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeUserAllNotificationStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChangeUserAllNotificationStatusReq) GetStatus() v1.NTF_STATUS {
	if x != nil {
		return x.Status
	}
	return v1.NTF_STATUS_INVALID
}

// 响应信息
type ChangeUserAllNotificationStatusRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeUserAllNotificationStatusRes) Reset() {
	*x = ChangeUserAllNotificationStatusRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserAllNotificationStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAllNotificationStatusRes) ProtoMessage() {}

func (x *ChangeUserAllNotificationStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAllNotificationStatusRes.ProtoReflect.Descriptor instead.
func (*ChangeUserAllNotificationStatusRes) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{14}
}

// SendMsgResponse发送消息响应结构
type SendMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息结果
	MsgResults []*MsgResult `protobuf:"bytes,1,rep,name=msgResults,proto3" json:"msgResults,omitempty"`
}

func (x *SendMsgRes) Reset() {
	*x = SendMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgRes) ProtoMessage() {}

func (x *SendMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgRes.ProtoReflect.Descriptor instead.
func (*SendMsgRes) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{15}
}

func (x *SendMsgRes) GetMsgResults() []*MsgResult {
	if x != nil {
		return x.MsgResults
	}
	return nil
}

type MsgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息返回码 0 - 成功，非0 - 失败
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 业务层扩展extra_id
	ExtraId string `protobuf:"bytes,2,opt,name=extraId,proto3" json:"extraId,omitempty"`
	// 消息结果id
	MsgId string `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// 消息结果原因
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *MsgResult) Reset() {
	*x = MsgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notify_v1_notify_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgResult) ProtoMessage() {}

func (x *MsgResult) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgResult.ProtoReflect.Descriptor instead.
func (*MsgResult) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{16}
}

func (x *MsgResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MsgResult) GetExtraId() string {
	if x != nil {
		return x.ExtraId
	}
	return ""
}

func (x *MsgResult) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_notify_v1_notify_proto protoreflect.FileDescriptor

var file_notify_v1_notify_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x1a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe0, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x42, 0x08, 0xfa,
	0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x12, 0x2f, 0x0a,
	0x09, 0x76, 0x61, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x52, 0x09, 0x76, 0x61, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x26,
	0x0a, 0x06, 0x76, 0x61, 0x72, 0x53, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6d, 0x73, 0x52, 0x06,
	0x76, 0x61, 0x72, 0x53, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x76, 0x61, 0x72, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0xf8, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x76, 0x61, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x56, 0x61, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04,
	0x76, 0x61, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x70, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x74, 0x70, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x1a, 0x37, 0x0a, 0x09, 0x56, 0x61, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x75, 0x0a, 0x06, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x54, 0x46, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x05, 0x0a, 0x03, 0x53, 0x6d, 0x73, 0x22, 0x49, 0x0a,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x63, 0x63, 0x22, 0x4c, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x61, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22,
	0x02, 0x20, 0x00, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x22, 0x2e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x29, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x17,
	0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x54,
	0x46, 0x2e, 0x54, 0x59, 0x50, 0x45, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x35, 0x0a,
	0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x12, 0x37, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0xb6, 0x02, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x27, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x54, 0x46, 0x2e, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x54, 0x46, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x22, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x19, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x54, 0x46, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x24, 0x0a, 0x22, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x22,
	0x42, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a,
	0x0a, 0x6d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x22, 0x67, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x74, 0x72, 0x61, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0xc4, 0x03, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x37, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x12, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73,
	0x12, 0x52, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x12, 0x7f, 0x0a, 0x1f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x6c, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c,
	0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x6c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x56, 0x69,
	0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x5e, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x6e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x42, 0x82, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2f, 0x76, 0x31, 0x3b, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4e, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notify_v1_notify_proto_rawDescOnce sync.Once
	file_notify_v1_notify_proto_rawDescData = file_notify_v1_notify_proto_rawDesc
)

func file_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_notify_v1_notify_proto_rawDescData)
	})
	return file_notify_v1_notify_proto_rawDescData
}

var file_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_notify_v1_notify_proto_goTypes = []interface{}{
	(*SendMsgReq)(nil),                         // 0: notify.v1.SendMsgReq
	(*Msg)(nil),                                // 1: notify.v1.Msg
	(*Letter)(nil),                             // 2: notify.v1.Letter
	(*Sms)(nil),                                // 3: notify.v1.Sms
	(*Email)(nil),                              // 4: notify.v1.Email
	(*UserNotification)(nil),                   // 5: notify.v1.UserNotification
	(*UpdateReadStatusReq)(nil),                // 6: notify.v1.UpdateReadStatusReq
	(*UpdateReadStatusRes)(nil),                // 7: notify.v1.UpdateReadStatusRes
	(*GetUnViewCountReq)(nil),                  // 8: notify.v1.GetUnViewCountReq
	(*GetUnViewCountRes)(nil),                  // 9: notify.v1.GetUnViewCountRes
	(*ListUserNotificationReq)(nil),            // 10: notify.v1.ListUserNotificationReq
	(*ListUserNotificationRes)(nil),            // 11: notify.v1.ListUserNotificationRes
	(*ListUserNotificationItem)(nil),           // 12: notify.v1.ListUserNotificationItem
	(*ChangeUserAllNotificationStatusReq)(nil), // 13: notify.v1.ChangeUserAllNotificationStatusReq
	(*ChangeUserAllNotificationStatusRes)(nil), // 14: notify.v1.ChangeUserAllNotificationStatusRes
	(*SendMsgRes)(nil),                         // 15: notify.v1.SendMsgRes
	(*MsgResult)(nil),                          // 16: notify.v1.MsgResult
	nil,                                        // 17: notify.v1.Msg.VarsEntry
	(v1.NTF_TYPE)(0),                           // 18: common.v1.NTF.TYPE
	(*v1.Pagination)(nil),                      // 19: common.v1.Pagination
	(v1.NTF_STATUS)(0),                         // 20: common.v1.NTF.STATUS
}
var file_notify_v1_notify_proto_depIdxs = []int32{
	1,  // 0: notify.v1.SendMsgReq.msgs:type_name -> notify.v1.Msg
	2,  // 1: notify.v1.SendMsgReq.varLetter:type_name -> notify.v1.Letter
	3,  // 2: notify.v1.SendMsgReq.varSms:type_name -> notify.v1.Sms
	4,  // 3: notify.v1.SendMsgReq.varEmail:type_name -> notify.v1.Email
	17, // 4: notify.v1.Msg.vars:type_name -> notify.v1.Msg.VarsEntry
	18, // 5: notify.v1.Letter.type:type_name -> common.v1.NTF.TYPE
	18, // 6: notify.v1.ListUserNotificationReq.types:type_name -> common.v1.NTF.TYPE
	19, // 7: notify.v1.ListUserNotificationReq.pagination:type_name -> common.v1.Pagination
	12, // 8: notify.v1.ListUserNotificationRes.list:type_name -> notify.v1.ListUserNotificationItem
	19, // 9: notify.v1.ListUserNotificationRes.pagination:type_name -> common.v1.Pagination
	18, // 10: notify.v1.ListUserNotificationItem.type:type_name -> common.v1.NTF.TYPE
	20, // 11: notify.v1.ListUserNotificationItem.status:type_name -> common.v1.NTF.STATUS
	20, // 12: notify.v1.ChangeUserAllNotificationStatusReq.status:type_name -> common.v1.NTF.STATUS
	16, // 13: notify.v1.SendMsgRes.msgResults:type_name -> notify.v1.MsgResult
	0,  // 14: notify.v1.Notify.SendMsg:input_type -> notify.v1.SendMsgReq
	6,  // 15: notify.v1.Notify.UpdateReadStatus:input_type -> notify.v1.UpdateReadStatusReq
	13, // 16: notify.v1.Notify.ChangeUserAllNotificationStatus:input_type -> notify.v1.ChangeUserAllNotificationStatusReq
	8,  // 17: notify.v1.Notify.GetUnViewCount:input_type -> notify.v1.GetUnViewCountReq
	10, // 18: notify.v1.Notify.ListUserNotification:input_type -> notify.v1.ListUserNotificationReq
	15, // 19: notify.v1.Notify.SendMsg:output_type -> notify.v1.SendMsgRes
	7,  // 20: notify.v1.Notify.UpdateReadStatus:output_type -> notify.v1.UpdateReadStatusRes
	14, // 21: notify.v1.Notify.ChangeUserAllNotificationStatus:output_type -> notify.v1.ChangeUserAllNotificationStatusRes
	9,  // 22: notify.v1.Notify.GetUnViewCount:output_type -> notify.v1.GetUnViewCountRes
	11, // 23: notify.v1.Notify.ListUserNotification:output_type -> notify.v1.ListUserNotificationRes
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_notify_v1_notify_proto_init() }
func file_notify_v1_notify_proto_init() {
	if File_notify_v1_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notify_v1_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Letter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReadStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReadStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnViewCountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnViewCountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserNotificationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserNotificationRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListUserNotificationItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserAllNotificationStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserAllNotificationStatusRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notify_v1_notify_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notify_v1_notify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_notify_v1_notify_proto_depIdxs,
		MessageInfos:      file_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_notify_v1_notify_proto = out.File
	file_notify_v1_notify_proto_rawDesc = nil
	file_notify_v1_notify_proto_goTypes = nil
	file_notify_v1_notify_proto_depIdxs = nil
}
