package space

import (
	"log"
	"strings"

	spacev1 "ecodepost/pb/space/v1"
	"ecodepost/resource-svc/pkg/invoker"
	"ecodepost/resource-svc/pkg/service"

	"github.com/BurntSushi/toml"
	"github.com/gotomicro/ego/core/econf"
	"github.com/gotomicro/ego/server/egrpc"
)

// svc generated by protoc-gen-go-test, you should not edit it.
// @Override=true
var svc *egrpc.Component

// init generated by protoc-gen-go-test, you can fill initial logic by yourself.
// @Override=true
func init() {
	conf := `

`
	// 加载配置
	err := econf.LoadFromReader(strings.NewReader(conf), toml.Unmarshal)
	if err != nil {
		log.Fatalf("init exited with error: %v", err)
	}
	// invoker.Db = egorm.Load("mysql").Build()
	invoker.Init()
	service.Init()
	// 初始化bufnet gRPC的测试服务
	svc = Server()

	err = svc.Init()
	if err != nil {
		log.Fatalf("init server with error: %v", err)
	}

	go func() {
		// 启动服务
		if err = svc.Start(); err != nil {
			log.Fatalf("Server exited with error: %v", err)
		}
	}()
}

func Server() *egrpc.Component {
	grpcCmp := egrpc.Load("server.grpc").Build()
	spacev1.RegisterSpaceServer(grpcCmp.Server, &GrpcServer{})
	return grpcCmp
}
