// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: common/v1/enum_course.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MLS:MemberLessonStatus 成员课程状态
type CRS_MLS int32

const (
	// 未知状态
	CRS_MLS_INVALID CRS_MLS = 0
	// 未完成
	CRS_MLS_UNCOMPLETED CRS_MLS = 10
	// 已完成
	CRS_MLS_COMPLETED CRS_MLS = 20
)

// Enum value maps for CRS_MLS.
var (
	CRS_MLS_name = map[int32]string{
		0:  "MLS_INVALID",
		10: "MLS_UNCOMPLETED",
		20: "MLS_COMPLETED",
	}
	CRS_MLS_value = map[string]int32{
		"MLS_INVALID":     0,
		"MLS_UNCOMPLETED": 10,
		"MLS_COMPLETED":   20,
	}
)

func (x CRS_MLS) Enum() *CRS_MLS {
	p := new(CRS_MLS)
	*p = x
	return p
}

func (x CRS_MLS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRS_MLS) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_course_proto_enumTypes[0].Descriptor()
}

func (CRS_MLS) Type() protoreflect.EnumType {
	return &file_common_v1_enum_course_proto_enumTypes[0]
}

func (x CRS_MLS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRS_MLS.Descriptor instead.
func (CRS_MLS) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_course_proto_rawDescGZIP(), []int{0, 0}
}

// CRS:COURSE 课程服务相关枚举值
type CRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CRS) Reset() {
	*x = CRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_enum_course_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRS) ProtoMessage() {}

func (x *CRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_enum_course_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRS.ProtoReflect.Descriptor instead.
func (*CRS) Descriptor() ([]byte, []int) {
	return file_common_v1_enum_course_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_enum_course_proto protoreflect.FileDescriptor

var file_common_v1_enum_course_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x5f, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x45, 0x0a, 0x03, 0x43, 0x52, 0x53, 0x22,
	0x3e, 0x0a, 0x03, 0x4d, 0x4c, 0x53, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x4c, 0x53, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x4c, 0x53, 0x5f, 0x55,
	0x4e, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x0a, 0x12, 0x11, 0x0a, 0x0d,
	0x4d, 0x4c, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x14, 0x42,
	0x86, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x42, 0x0f, 0x45, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_enum_course_proto_rawDescOnce sync.Once
	file_common_v1_enum_course_proto_rawDescData = file_common_v1_enum_course_proto_rawDesc
)

func file_common_v1_enum_course_proto_rawDescGZIP() []byte {
	file_common_v1_enum_course_proto_rawDescOnce.Do(func() {
		file_common_v1_enum_course_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_enum_course_proto_rawDescData)
	})
	return file_common_v1_enum_course_proto_rawDescData
}

var file_common_v1_enum_course_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_enum_course_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_enum_course_proto_goTypes = []interface{}{
	(CRS_MLS)(0), // 0: common.v1.CRS.MLS
	(*CRS)(nil),  // 1: common.v1.CRS
}
var file_common_v1_enum_course_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_enum_course_proto_init() }
func file_common_v1_enum_course_proto_init() {
	if File_common_v1_enum_course_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_enum_course_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_enum_course_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_enum_course_proto_goTypes,
		DependencyIndexes: file_common_v1_enum_course_proto_depIdxs,
		EnumInfos:         file_common_v1_enum_course_proto_enumTypes,
		MessageInfos:      file_common_v1_enum_course_proto_msgTypes,
	}.Build()
	File_common_v1_enum_course_proto = out.File
	file_common_v1_enum_course_proto_rawDesc = nil
	file_common_v1_enum_course_proto_goTypes = nil
	file_common_v1_enum_course_proto_depIdxs = nil
}
