// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: common/v1/enum_notify.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CHANNEL:ChannelType 通道类型
type NOTIFY_CHANNEL int32

const (
	// 未知类型
	NOTIFY_CHANNEL_INVALID NOTIFY_CHANNEL = 0
	// 邮件
	NOTIFY_CHANNEL_EMAIL_COMMON NOTIFY_CHANNEL = 1
	// 短信
	NOTIFY_CHANNEL_SMS_ALI NOTIFY_CHANNEL = 2
	// 站内信
	NOTIFY_CHANNEL_LETTER NOTIFY_CHANNEL = 3
)

// Enum value maps for NOTIFY_CHANNEL.
var (
	NOTIFY_CHANNEL_name = map[int32]string{
		0: "CHANNEL_INVALID",
		1: "CHANNEL_EMAIL_COMMON",
		2: "CHANNEL_SMS_ALI",
		3: "CHANNEL_LETTER",
	}
	NOTIFY_CHANNEL_value = map[string]int32{
		"CHANNEL_INVALID":      0,
		"CHANNEL_EMAIL_COMMON": 1,
		"CHANNEL_SMS_ALI":      2,
		"CHANNEL_LETTER":       3,
	}
)

func (x NOTIFY_CHANNEL) Enum() *NOTIFY_CHANNEL {
	p := new(NOTIFY_CHANNEL)
	*p = x
	return p
}

func (x NOTIFY_CHANNEL) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFY_CHANNEL) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_notify_proto_enumTypes[0].Descriptor()
}

func (NOTIFY_CHANNEL) Type() protoreflect.EnumType {
	return &file_common_v1_enum_notify_proto_enumTypes[0]
}

func (x NOTIFY_CHANNEL) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFY_CHANNEL.Descriptor instead.
func (NOTIFY_CHANNEL) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{0, 0}
}

// MS: MsgStatus 消息状态
type NOTIFY_STATUS int32

const (
	// 未知状态
	NOTIFY_STATUS_INVALID NOTIFY_STATUS = 0
	// 初始化状态
	NOTIFY_STATUS_INIT NOTIFY_STATUS = 1
	// 发送中
	NOTIFY_STATUS_SENDING NOTIFY_STATUS = 2
	// 发送成功
	NOTIFY_STATUS_SUCCESS NOTIFY_STATUS = 3
	// 发送失败
	NOTIFY_STATUS_ERROR NOTIFY_STATUS = 4
)

// Enum value maps for NOTIFY_STATUS.
var (
	NOTIFY_STATUS_name = map[int32]string{
		0: "STATUS_INVALID",
		1: "STATUS_INIT",
		2: "STATUS_SENDING",
		3: "STATUS_SUCCESS",
		4: "STATUS_ERROR",
	}
	NOTIFY_STATUS_value = map[string]int32{
		"STATUS_INVALID": 0,
		"STATUS_INIT":    1,
		"STATUS_SENDING": 2,
		"STATUS_SUCCESS": 3,
		"STATUS_ERROR":   4,
	}
)

func (x NOTIFY_STATUS) Enum() *NOTIFY_STATUS {
	p := new(NOTIFY_STATUS)
	*p = x
	return p
}

func (x NOTIFY_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFY_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_notify_proto_enumTypes[1].Descriptor()
}

func (NOTIFY_STATUS) Type() protoreflect.EnumType {
	return &file_common_v1_enum_notify_proto_enumTypes[1]
}

func (x NOTIFY_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFY_STATUS.Descriptor instead.
func (NOTIFY_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{0, 1}
}

// CS:CheckStatus 审核状态
type NOTIFY_CS int32

const (
	// 未知状态
	NOTIFY_CS_INVALID NOTIFY_CS = 0
	// 审核中
	NOTIFY_CS_CHECKING NOTIFY_CS = 1
	// 审核通过
	NOTIFY_CS_SUCCESS NOTIFY_CS = 2
	// 审核未通过
	NOTIFY_CS_FAIL NOTIFY_CS = 3
)

// Enum value maps for NOTIFY_CS.
var (
	NOTIFY_CS_name = map[int32]string{
		0: "CS_INVALID",
		1: "CS_CHECKING",
		2: "CS_SUCCESS",
		3: "CS_FAIL",
	}
	NOTIFY_CS_value = map[string]int32{
		"CS_INVALID":  0,
		"CS_CHECKING": 1,
		"CS_SUCCESS":  2,
		"CS_FAIL":     3,
	}
)

func (x NOTIFY_CS) Enum() *NOTIFY_CS {
	p := new(NOTIFY_CS)
	*p = x
	return p
}

func (x NOTIFY_CS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFY_CS) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_notify_proto_enumTypes[2].Descriptor()
}

func (NOTIFY_CS) Type() protoreflect.EnumType {
	return &file_common_v1_enum_notify_proto_enumTypes[2]
}

func (x NOTIFY_CS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFY_CS.Descriptor instead.
func (NOTIFY_CS) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{0, 2}
}

// TYPE:NotificationType 消息通知类型
type NTF_TYPE int32

const (
	// 未知类型
	NTF_TYPE_INVALID NTF_TYPE = 0
	// 系统通知
	NTF_TYPE_SYSTEM NTF_TYPE = 1
	// 团队加入邀请
	NTF_TYPE_INVITE NTF_TYPE = 3
	// 审核通知
	NTF_TYPE_AUDIT NTF_TYPE = 5
	// 新的被@通知
	NTF_TYPE_NEW_MENTION NTF_TYPE = 6
	// 新的评论通知
	NTF_TYPE_NEW_COMMENT NTF_TYPE = 7
	// 申请加入空间通知
	NTF_TYPE_APPLY_SPACE NTF_TYPE = 8
	// 申请加入空间分组通知
	NTF_TYPE_APPLY_SPACE_GROUP NTF_TYPE = 9
	// 新回答通知
	NTF_TYPE_NEW_ANSWER NTF_TYPE = 10
)

// Enum value maps for NTF_TYPE.
var (
	NTF_TYPE_name = map[int32]string{
		0:  "TYPE_INVALID",
		1:  "TYPE_SYSTEM",
		3:  "TYPE_INVITE",
		5:  "TYPE_AUDIT",
		6:  "TYPE_NEW_MENTION",
		7:  "TYPE_NEW_COMMENT",
		8:  "TYPE_APPLY_SPACE",
		9:  "TYPE_APPLY_SPACE_GROUP",
		10: "TYPE_NEW_ANSWER",
	}
	NTF_TYPE_value = map[string]int32{
		"TYPE_INVALID":           0,
		"TYPE_SYSTEM":            1,
		"TYPE_INVITE":            3,
		"TYPE_AUDIT":             5,
		"TYPE_NEW_MENTION":       6,
		"TYPE_NEW_COMMENT":       7,
		"TYPE_APPLY_SPACE":       8,
		"TYPE_APPLY_SPACE_GROUP": 9,
		"TYPE_NEW_ANSWER":        10,
	}
)

func (x NTF_TYPE) Enum() *NTF_TYPE {
	p := new(NTF_TYPE)
	*p = x
	return p
}

func (x NTF_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NTF_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_notify_proto_enumTypes[3].Descriptor()
}

func (NTF_TYPE) Type() protoreflect.EnumType {
	return &file_common_v1_enum_notify_proto_enumTypes[3]
}

func (x NTF_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NTF_TYPE.Descriptor instead.
func (NTF_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{1, 0}
}

// STS:STATUS 通知状态
type NTF_STATUS int32

const (
	// 用户通知状态：无效枚举值
	NTF_STATUS_INVALID NTF_STATUS = 0
	// 用户通知状态：已读
	NTF_STATUS_READED NTF_STATUS = 1
	// 用户通知状态：未读
	NTF_STATUS_UNREADED NTF_STATUS = 2
)

// Enum value maps for NTF_STATUS.
var (
	NTF_STATUS_name = map[int32]string{
		0: "STATUS_INVALID",
		1: "STATUS_READED",
		2: "STATUS_UNREADED",
	}
	NTF_STATUS_value = map[string]int32{
		"STATUS_INVALID":  0,
		"STATUS_READED":   1,
		"STATUS_UNREADED": 2,
	}
)

func (x NTF_STATUS) Enum() *NTF_STATUS {
	p := new(NTF_STATUS)
	*p = x
	return p
}

func (x NTF_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NTF_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_enum_notify_proto_enumTypes[4].Descriptor()
}

func (NTF_STATUS) Type() protoreflect.EnumType {
	return &file_common_v1_enum_notify_proto_enumTypes[4]
}

func (x NTF_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NTF_STATUS.Descriptor instead.
func (NTF_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{1, 1}
}

// NOTIFY:NOTIFY 相关枚举值
type NOTIFY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NOTIFY) Reset() {
	*x = NOTIFY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_enum_notify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NOTIFY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NOTIFY) ProtoMessage() {}

func (x *NOTIFY) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_enum_notify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NOTIFY.ProtoReflect.Descriptor instead.
func (*NOTIFY) Descriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{0}
}

// NTF:Notify 通知相关enum
type NTF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NTF) Reset() {
	*x = NTF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_enum_notify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NTF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NTF) ProtoMessage() {}

func (x *NTF) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_enum_notify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NTF.ProtoReflect.Descriptor instead.
func (*NTF) Descriptor() ([]byte, []int) {
	return file_common_v1_enum_notify_proto_rawDescGZIP(), []int{1}
}

var File_common_v1_enum_notify_proto protoreflect.FileDescriptor

var file_common_v1_enum_notify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x98, 0x02, 0x0a, 0x06, 0x4e, 0x4f, 0x54,
	0x49, 0x46, 0x59, 0x22, 0x61, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x12, 0x13,
	0x0a, 0x0f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x45,
	0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x53, 0x4d, 0x53, 0x5f, 0x41, 0x4c, 0x49,
	0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x4c, 0x45,
	0x54, 0x54, 0x45, 0x52, 0x10, 0x03, 0x22, 0x67, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49,
	0x4e, 0x49, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x53, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22,
	0x42, 0x0a, 0x02, 0x43, 0x53, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x53, 0x5f, 0x43, 0x48, 0x45, 0x43,
	0x4b, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x53, 0x5f, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x53, 0x5f, 0x46, 0x41, 0x49,
	0x4c, 0x10, 0x03, 0x22, 0x8b, 0x02, 0x0a, 0x03, 0x4e, 0x54, 0x46, 0x22, 0xbd, 0x01, 0x0a, 0x04,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53,
	0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x41, 0x55, 0x44, 0x49, 0x54, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x4d, 0x45, 0x4e, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06, 0x12, 0x14,
	0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45,
	0x4e, 0x54, 0x10, 0x07, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x50, 0x50,
	0x4c, 0x59, 0x5f, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x08, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x59, 0x5f, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x47,
	0x52, 0x4f, 0x55, 0x50, 0x10, 0x09, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e,
	0x45, 0x57, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x0a, 0x22, 0x44, 0x0a, 0x06, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x41, 0x44, 0x45, 0x44, 0x10,
	0x02, 0x42, 0x86, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x42, 0x0f, 0x45, 0x6e, 0x75, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x74, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x09,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5c, 0x56,
	0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0a,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_v1_enum_notify_proto_rawDescOnce sync.Once
	file_common_v1_enum_notify_proto_rawDescData = file_common_v1_enum_notify_proto_rawDesc
)

func file_common_v1_enum_notify_proto_rawDescGZIP() []byte {
	file_common_v1_enum_notify_proto_rawDescOnce.Do(func() {
		file_common_v1_enum_notify_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_enum_notify_proto_rawDescData)
	})
	return file_common_v1_enum_notify_proto_rawDescData
}

var file_common_v1_enum_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_v1_enum_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_enum_notify_proto_goTypes = []interface{}{
	(NOTIFY_CHANNEL)(0), // 0: common.v1.NOTIFY.CHANNEL
	(NOTIFY_STATUS)(0),  // 1: common.v1.NOTIFY.STATUS
	(NOTIFY_CS)(0),      // 2: common.v1.NOTIFY.CS
	(NTF_TYPE)(0),       // 3: common.v1.NTF.TYPE
	(NTF_STATUS)(0),     // 4: common.v1.NTF.STATUS
	(*NOTIFY)(nil),      // 5: common.v1.NOTIFY
	(*NTF)(nil),         // 6: common.v1.NTF
}
var file_common_v1_enum_notify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_enum_notify_proto_init() }
func file_common_v1_enum_notify_proto_init() {
	if File_common_v1_enum_notify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_enum_notify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NOTIFY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_enum_notify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NTF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_enum_notify_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_enum_notify_proto_goTypes,
		DependencyIndexes: file_common_v1_enum_notify_proto_depIdxs,
		EnumInfos:         file_common_v1_enum_notify_proto_enumTypes,
		MessageInfos:      file_common_v1_enum_notify_proto_msgTypes,
	}.Build()
	File_common_v1_enum_notify_proto = out.File
	file_common_v1_enum_notify_proto_rawDesc = nil
	file_common_v1_enum_notify_proto_goTypes = nil
	file_common_v1_enum_notify_proto_depIdxs = nil
}
