// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/v1/enum_common.proto

package commonv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CMN with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *CMN) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CMN with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in CMNMultiError, or nil if none found.
func (m *CMN) ValidateAll() error {
	return m.validate(true)
}

func (m *CMN) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CMNMultiError(errors)
	}

	return nil
}

// CMNMultiError is an error wrapping multiple validation errors returned by
// CMN.ValidateAll() if the designated constraints aren't met.
type CMNMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CMNMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CMNMultiError) AllErrors() []error { return m }

// CMNValidationError is the validation error returned by CMN.Validate if the
// designated constraints aren't met.
type CMNValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CMNValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CMNValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CMNValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CMNValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CMNValidationError) ErrorName() string { return "CMNValidationError" }

// Error satisfies the builtin error interface
func (e CMNValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCMN.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CMNValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CMNValidationError{}
